version: '2.2'
services:

  django:
    build: .
    # Loading the app is defined here to allow for
    # autoreload on changes it is mounted on top of the
    # old copy that docker added when creating the image
    volumes:
      - '.:/usr/src/app'
    environment:
      - DEBUG=False
      - GEONODE_LB_HOST_IP=localhost
      - GEONODE_LB_PORT=80
      - SITEURL=http://localhost/
      - ALLOWED_HOSTS=['localhost', ]
      - GEOSERVER_PUBLIC_LOCATION=http://localhost/geoserver/
      - GEOSERVER_WEB_UI_LOCATION=http://localhost/geoserver/

  celery:
    build: .
    environment:
      - DEBUG=False
      - GEONODE_LB_HOST_IP=localhost
      - GEONODE_LB_PORT=80
      - SITEURL=http://localhost/
      - ALLOWED_HOSTS=['localhost', ]
      - GEOSERVER_PUBLIC_LOCATION=http://localhost/geoserver/
      - GEOSERVER_WEB_UI_LOCATION=http://localhost/geoserver/

  geoserver:
    environment:
      - GEONODE_LB_HOST_IP=localhost
      - GEONODE_LB_PORT=80
