name: "[52n_master -> lastest] Builds GeoNode Docker Images"

concurrency:
  group: "geonode_build_master"
  cancel-in-progress: true

env:
  TITLE: "52°North GeoNode Docker Image"
  VENDOR: "52°North GmbH"
  AUTHORS: "https://52North.org/"
  DESCRIPTION: "Builds and publishes the Docker images GeoNode, GeoServer, Nginx"
  LICENSE: "GPL-3.0"
  TAG: latest

on:
  push:
    branches:
      - "52n-master"

jobs:
  build_and_push_geonode:
    runs-on: ubuntu-22.04
    env:
      IMAGE: 52north/geonode
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE }}
          labels: |
            "org.opencontainers.image.authors=${{ env.AUTHORS }}"
            "org.opencontainers.image.vendor=${{ env.VENDOR }}"
            "org.opencontainers.image.description=${{ env.DESCRIPTION }}"
            "org.opencontainers.image.title=${{ env.TITLE }}"
            "org.opencontainers.image.licenses=${{ env.LICENSE }}"
          tags: |
            ${{ env.TAG }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN_52N_MASTER }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE }}:buildcache,mode=max

  build_and_push_nginx:
    runs-on: ubuntu-22.04
    env:
      IMAGE: 52north/geonode-nginx
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE }}
          labels: |
            "org.opencontainers.image.authors=${{ env.AUTHORS }}"
            "org.opencontainers.image.vendor=${{ env.VENDOR }}"
            "org.opencontainers.image.description=${{ env.DESCRIPTION }}"
            "org.opencontainers.image.title=${{ env.TITLE }}"
            "org.opencontainers.image.licenses=${{ env.LICENSE }}"
          tags: |
            ${{ env.TAG }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN_52N_MASTER }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./scripts/docker/nginx/
          file: ./scripts/docker/nginx/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE }}:buildcache,mode=max

  build_and_push_geoserver:
    runs-on: ubuntu-22.04
    env:
      IMAGE: 52north/geonode-geoserver
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: "${{ env.IMAGE }}"
          labels: |
            "org.opencontainers.image.authors=${{ env.AUTHORS }}"
            "org.opencontainers.image.vendor=${{ env.VENDOR }}"
            "org.opencontainers.image.description=${{ env.DESCRIPTION }}"
            "org.opencontainers.image.title=${{ env.TITLE }}"
            "org.opencontainers.image.licenses=${{ env.LICENSE }}"
          tags: |
            ${{ env.TAG }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN_52N_MASTER }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./scripts/docker/geoserver/
          file: ./scripts/docker/geoserver/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE }}:buildcache,mode=max
